import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/app/context/AuthContext"; // Thêm AuthProvider
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased">
        <AuthProvider> {/* Bọc toàn bộ ứng dụng trong AuthProvider */}
          <Toaster />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
